{
 "title": "iSpindel",
 "description": "iSpindel",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "InfluxDB Bucket", "query": "buckets()" },
   {
    "name": "ispindel",
    "label": "iSpindel",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n  bucket: \"iSpindel\",\n  measurement: \"measurements\",\n  tag: \"source\",\n  start: -10y\n)"
   },
   { "name": "calibration0", "label": "Calibration factor 0", "query": "${VAR_CALIBRATION0}" },
   { "name": "calibration1", "label": "Calibration factor 1", "query": "${VAR_CALIBRATION1}" },
   { "name": "calibration2", "label": "Calibration factor 2", "query": "${VAR_CALIBRATION2}" },
   { "name": "calibration3", "label": "Calibration factor 3", "query": "${VAR_CALIBRATION3}" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Gravity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expression": "(-1*616.868)+(1111.14*$C)-(630.272*$C*$C)+(135.997*$C*$C*$C)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Specific Gravity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "(${calibration3}*$A*$A*$A)+(${calibration2}*$A*$A)+(${calibration1}*$A)+(${calibration0})",
     "type": "math"
    }
   ]
  },
  {
   "title": "Tilt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tilt\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> last()"
    }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RSSI\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Gravity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expression": "(-1*616.868)+(1111.14*$C)-(630.272*$C*$C)+(135.997*$C*$C*$C)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Specific Gravity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "(${calibration3}*$A*$A*$A)+(${calibration2}*$A*$A)+(${calibration1}*$A)+(${calibration0})",
     "type": "math"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Tilt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tilt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"source\"] == \"${ispindel}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RSSI\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}